spring:
  datasource:
    password: Sapatada1982#
    username: root
    url: 'jdbc:mysql://localhost/fornecedor?characterEncoding=utf8&useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.hbm2ddl.auto = update'
  jpa:
    hibernate:
      ddl-auto: update
